# Use - instead of . when specifying your hostnames
# Supply a list of commands that shall be ran, %s will be replaced with the player's name upon execution.
# Use /bfh reload to reload this file.
example-com:
  - "tellraw %s {\"text\":\"Hello\"}"